### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by svenschneider** [rockin-robot-challenge/benchmark_and_scoring_fbm#2]
There are some naming inconsistencies in this package:
- The repository is called "benchmark_and_scoring_fbm"
- The Catkin/ROS package is called "rockin_scoring"
- In some (all?) of the Python scripts, the messages are imported from the package "rockin_benchmarking"

Especially the last point results in failures (see below) when we try to execute the ROS nodes.

```
# roslaunch rockin_scoring fbm1h.launch 
... logging to ~/.ros/log/5aa18418-1980-11e5-92bd-0090f5edbfda/roslaunch-pc-6125.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:44549/

SUMMARY
========

PARAMETERS
 * /fbm1h/items
 * /rosdistro
 * /rosversion

NODES
  /fbm1h/
    benchmark (rockin_scoring/fbm1h)

auto-starting new master
process[master]: started with pid [6141]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5aa18418-1980-11e5-92bd-0090f5edbfda
process[rosout-1]: started with pid [6154]
started core service [/rosout]
process[fbm1h/benchmark-2]: started with pid [6157]
Traceback (most recent call last):
  File "<catkin_ws>/src/benchmark_and_scoring_fbm/scripts/fbm1h", line 10, in <module>
    from rockin_benchmarking.BmBox import BmBox
  File "<catkin_ws>/src/benchmark_and_scoring_fbm/src/rockin_benchmarking/BmBox.py", line 4, in <module>
    from rockin_benchmarking.msg import BmBoxState, RefBoxState, ClientState
ImportError: No module named msg
[fbm1h/benchmark-2] process has died [pid 6157, exit code 1, cmd <catkin_ws>/src/benchmark_and_scoring_fbm/scripts/fbm1h __name:=benchmark __log:=~/.ros/log/5aa18418-1980-11e5-92bd-0090f5edbfda/fbm1h-benchmark-2.log].
log file: ~/.ros/log/5aa18418-1980-11e5-92bd-0090f5edbfda/fbm1h-benchmark-2*.log
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

Which of the above names should we use?

**Comment by tinito** [comment]
Sorry, the package was named rockin_benchmarking but later it was splitted into rockin_scoring and rockin_mocap.
The correct package name for the benchmark scripts is rockin_scoring.
I've fixed the message imports, it should be OK now.

The repository was not created by me so I did not choose the name :)

**Comment by Marc43** [comment]
Hi, I think there are some inconsistencies that still:

- The steps I followed at the git repository of the at_home_rsbb package made me download roah_devices and roah_benchmarking, but at_home_rsbb actually searchs for rockin_scoring.

So, I found another package, benchmark_and_scoring_fbm which works a little bit more than the last configuration of packages.

Which package I have to use?
Why is crashing?

The error I get is:
```
Invalid <arg> tag: rockin_scoring
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/humanoide/tiago_public_ws/src
ROS path [2]=/opt/ros/indigo/share
ROS path [3]=/opt/ros/indigo/stacks. 

Arg xml is <arg default="$(find rockin_scoring)/config/fbm2h.yaml" name="fbm2_locations_file"/>
The traceback for the exception was written to the log file
```
